// try catch

const num1 = 20;
const num2 = 30;
const num4 = 40;

console.log(num1);
console.log(num2);
try {
    console.log(num3);
} catch (error) {
    console.log(error);
}
console.log(num4);